name: release
on:
  push:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout t88
        uses: actions/checkout@v4
        with:
          repository: USS-Shenzhou/t88
          path: t88

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: main

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Publish t88 to Maven Local
        working-directory: t88
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal

      - name: Maven Publish
        id: maven_publish
        working-directory: main
        env:
          ARCHIVE_URL: ${{ secrets.TEACON_ARCHIVE_URL }}
          ARCHIVE_ENDPOINT: ${{ secrets.TEACON_ARCHIVE_ENDPOINT }}
          ARCHIVE_ACCESS_KEY: ${{ secrets.TEACON_ARCHIVE_ACCESS_KEY }}
          ARCHIVE_SECRET_KEY: ${{ secrets.TEACON_ARCHIVE_SECRET_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew -Dorg.gradle.s3.endpoint=$ARCHIVE_ENDPOINT publish
